enum Configure;
enum Thread;
struct Center;
typedef void (*xftype)(enum Configure, int sav, int val);
typedef void (*mftype)(enum Thread tag, int idx);
typedef void (*wftype)(int pass, struct Center *center);
typedef void (*nftype)(struct Center *center, wftype pass);
typedef void (*oftype)(enum Configure cfg, xftype back);
typedef void (*vftype)(enum Thread thd, int idx, mftype call, mftype done, mftype func);
void planeInit(nftype copy, oftype call, vftype fork, wftype pass);
int planeLoop();
