enum Configure;
enum Thread;
struct Extend;
typedef void (*mftype)(enum Thread tag, int idx);
typedef void (*xftype)(enum Configure cfg, int sav, int val, int act);
typedef void (*nftype)(enum Configure cfg, xftype back);
typedef void (*vftype)(enum Thread thd, int idx, mftype call, mftype done, mftype heap, mftype wake);
typedef int (*yftype)(int *ref, int val);
typedef void (*zftype)(enum Configure *cfg, int *val, int siz, yftype fnc);
typedef const char *(*oftype)(int arg);
typedef void (*aftype)();
typedef int (*bftype)();
typedef void (*uftype)(struct Extend *ptr, int ary, const char *dbg);
typedef void (*wftype)(struct Extend *ptr, int ary, int log);
void planeInit(uftype copy, wftype cont, nftype call, vftype fork, zftype gnfo, zftype info, zftype jnfo, zftype knfo, bftype hnfo, oftype cmnd, aftype wait, aftype wake);
int planeLoop();
void planeDone();
void centerDone(struct Extend *ptr);
int centerMod(struct Extend *ptr);
