enum Configure;
enum Thread;
struct Center;
typedef void (*mftype)(enum Thread tag, int idx);
typedef void (*wftype)(struct Center *ptr, int sub);
typedef void (*xftype)(enum Configure cfg, int sav, int val, int act);
typedef void (*nftype)(enum Configure cfg, xftype back);
typedef void (*vftype)(enum Thread thd, int idx, mftype call, mftype done, mftype heap, mftype wake);
typedef int (*yftype)(int *ref, int val);
typedef int (*zftype)(enum Configure cfg, int val, yftype fnc);
typedef const char *(*oftype)(int arg);
struct Fnc {wftype pnow, pass, fnow, fail; int goon;};
typedef void (*uftype)(struct Center *ptr, int sub, struct Fnc fnc);
typedef void (*aftype)();
void planeInit(uftype copy, nftype call, vftype fork, zftype info, zftype jnfo, zftype knfo, oftype cmnd);
int planeLoop();
void planeDone();
void planePass(struct Center *ptr, int sub);
void planeFail(struct Center *ptr, int sub);
void planeTest(float *model, float *view, float *proj, float *debug);
struct Center *centerPull(int idx);
void centerPlace(struct Center *ptr, int idx);
int centerCheck(int idx);
int centerMod(struct Center *ptr);
